--- 
title: "[2019 UST 일반강의] R 프로그래밍과 데이터 분석"
author: "Haseong Kim"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: https://greendaygh.github.io/Rprog2019/
description: "2019년 UST 강의 R 프로그래밍 웹사이트"
---


# Lecture 개요 
- 장소: 한국생명공학연구원 연구동 세미나실 1213호 (매주수요일 13:00~16:00)
- 강사: 한국생명공학연구원 바이오합성연구센터 김하성
- 연락처: 042-860-4372, haseong@kribb.re.kr (생명연 연구동 1143)

## Goal 강의 목표
- 이공계열 대학원생이 통계 분석용 범용 프로그램 언어인 R의 사용법을 익히고 이를 이용한 프로그래밍 기술의 습득을 주요 목적으로 함. 생물 데이터 위주의 분석 예제를 통해 R의 활용 기술을 배움. 
- 이 강좌는 오프라인 강의를 기본으로 함. R 사용에 대한 기본 개념과 프로그래밍을 중심으로 필요시 기초 통계지식 강의. 실습 데이터로는 주로 생물데이터를 사용함. 모든 강의 시간 실습을 위한 개인 노트북 지참 필수. 강의 자료는 pdf로 제작하여 수업 진행과 관련된 정보와 함께 웹사이트를 통해 배포됨. 상황에 따라 강의 일정이 조정될 수 있음.


## References 참고 자료
- R for Data Science (https://r4ds.had.co.nz, https://github.com/hadley)
- Using R for Introductory Statistics by John Verzani
  - Free version of 1st Edition 
    - https://cran.r-project.org/doc/contrib/Verzani-SimpleR.pdf
    - http://cbb.sjtu.edu.cn/~mywu/bi217/usingR.pdf
  - Second edition
    - https://www.crcpress.com/Using-R-for-Introductory-Statistics-Second-Edition/Verzani/p/book/9781466590731
- Bioinformatics Data Skills by Vince Buffalo
- https://resources.rstudio.com/
- 일반통계학 (영지문화사, 김우철 외)

## Evaluation 평가 세부 항목
- 출석 50% / 과제 50% / 수업참여 +alpha

## Schedule 강의 계획
- Introduction and installation of R/Rstudio
- R language basics 
- Data manipulation 
- Visualizing data in R 
- Shiny for interactive applications in R
- Workflows with R scripts
- Working with Range Data 
- Sequence analysis 
- Clustering and significance testing with genomic data 

## Lecture note 강의 자료
- 1 (2019.03.06) - [Introduction and installation of R/Rstudio, Basics of variables and functions](https://github.com/greendaygh/2019-R-programming/blob/master/01-Rprog.pdf)

- 2 (2019.03.13) - [R Basics - Objects (vector, factor, matrix) and functions](https://github.com/greendaygh/2019-R-programming/blob/master/02-Rprog.pdf) 다음 시간 readxl, Biostrings 두 패키지 미리 설치한 후 강의 참석 부탁드립니다.  

- 3 (2019.03.20) - [R Basics II - file I/O ](https://github.com/greendaygh/2019-R-programming/blob/master/03-Rprog.pdf)  강의가 좀 빠르게 진행된 듯 합니다. 기본으로 제공되는 R 기능을 사용하기 보다는 함수나 프로그래밍 코딩 원리를 이해하기 위해 직접 함수를 만들어보는 연습을 하고 있으니 참고 하시고 다음 시간 전에 이번 시간 코드 복습하시고 오시면 도움이 되실 것 같습니다. 

- 4 (2019.03.27) - [R programming example - Maze Robot ](https://github.com/greendaygh/2019-R-programming/blob/master/04-Rprog.pdf) 

